#
# Copyright 2018 Techyauld LLC
#

##################################################
# UART Sources
##################################################
UART_LIB_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../xilinx/uart/, \
slib_clock_div.vhd \
slib_counter.vhd \
slib_edge_detect.vhd \
slib_fifo.vhd \
slib_input_filter.vhd \
slib_input_sync.vhd \
slib_mv_filter.vhd \
uart_16750.vhd \
uart_baudgen.vhd \
uart_interrupt.vhd \
uart_receiver.vhd \
uart_transmitter.vhd \
))
