# set_property MARK_DEBUG true [get_nets clk_33m]
# set_property MARK_DEBUG true [get_nets CLK100MHZ_IBUF]
# set_property MARK_DEBUG true [get_nets {u_uart/A[1]}]
# set_property MARK_DEBUG true [get_nets {u_uart/A[2]}]
# set_property MARK_DEBUG true [get_nets {u_uart/A[0]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[0]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[1]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[2]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[3]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[4]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[5]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[6]}]
# set_property MARK_DEBUG true [get_nets {u_uart/DOUT[7]}]
# set_property MARK_DEBUG true [get_nets u_uart/iRXFIFORead]
# set_property MARK_DEBUG true [get_nets u_uart/RD]
# set_property MARK_DEBUG true [get_nets u_uart/SIN]

# create_debug_core u_ila_0 ila
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
# set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
# set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
# set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
# set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
# set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
# set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
# set_property port_width 1 [get_debug_ports u_ila_0/clk]
# connect_debug_port u_ila_0/clk [get_nets [list CLK100MHZ_IBUF]]

# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
# set_property port_width 1 [get_debug_ports u_ila_0/probe0]
# connect_debug_port u_ila_0/probe0 [get_nets [list clk_33m]]

# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
# set_property port_width 1 [get_debug_ports u_ila_0/probe1]
# connect_debug_port u_ila_0/probe1 [get_nets [list u_uart/RD]]

# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
# set_property port_width 1 [get_debug_ports u_ila_0/probe2]
# connect_debug_port u_ila_0/probe2 [get_nets [list u_uart/iRXFIFORead]]

# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
# set_property port_width 3 [get_debug_ports u_ila_0/probe3]
# connect_debug_port u_ila_0/probe3 [get_nets [list {u_uart/A[0]} {u_uart/A[1]} {u_uart/A[2]}]]

# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
# set_property port_width 8 [get_debug_ports u_ila_0/probe4]
# connect_debug_port u_ila_0/probe4 [get_nets [list {u_uart/DOUT[0]} {u_uart/DOUT[1]} {u_uart/DOUT[2]} {u_uart/DOUT[3]} {u_uart/DOUT[4]} {u_uart/DOUT[5]} {u_uart/DOUT[6]} {u_uart/DOUT[7]}]]

# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
# set_property port_width 1 [get_debug_ports u_ila_0/probe5]
# connect_debug_port u_ila_0/probe5 [get_nets [list u_uart/SIN]]

# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
# set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
# set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
# connect_debug_port dbg_hub/clk [get_nets CLK100MHZ_IBUF]


set_property MARK_DEBUG true [get_nets {app_rd_data[230]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[238]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[247]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[255]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[125]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[110]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[101]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[117]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[134]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[142]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[150]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[158]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[166]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[174]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[182]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[189]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[198]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[206]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[214]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[222]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[35]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[1]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[17]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[10]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[26]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[50]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[41]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[47]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[58]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[65]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[75]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[81]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[91]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[228]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[236]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[245]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[253]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[115]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[126]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[109]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[103]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[133]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[149]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[165]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[181]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[197]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[221]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[207]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[191]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[175]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[159]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[143]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[118]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[33]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[24]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[18]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[2]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[5]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[49]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[42]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[66]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[57]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[82]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[74]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[98]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[90]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[229]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[237]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[243]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[249]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[252]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[124]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[107]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[99]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[116]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[130]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[138]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[147]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[154]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[163]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[170]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[179]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[186]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[195]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[202]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[211]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[218]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[32]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[29]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[0]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[16]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[8]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[40]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[64]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[55]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[80]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[72]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[96]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[88]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[25]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[227]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[235]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[244]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[251]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[132]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[123]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[108]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[97]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[100]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[140]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[148]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[156]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[164]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[172]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[180]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[188]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[196]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[204]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[212]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[220]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[23]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[31]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[15]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[7]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[48]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[39]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[62]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[56]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[79]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[70]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[95]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[86]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[231]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[234]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[242]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[129]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[106]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[112]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[120]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[185]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[194]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[201]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[210]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[217]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[226]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[178]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[169]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[162]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[153]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[146]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[137]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[22]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[9]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[14]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[12]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[46]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[37]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[63]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[54]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[73]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[71]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[89]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[87]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[233]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[241]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[250]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[155]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[105]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[114]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[139]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[171]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[187]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[190]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[203]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[205]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[219]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[225]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[173]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[157]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[141]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[122]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[131]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[44]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[6]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[30]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[20]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[61]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[52]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[78]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[69]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[94]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[85]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[38]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[213]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[239]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[248]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[128]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[102]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[111]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[119]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[192]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[199]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[208]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[215]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[223]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[183]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[176]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[167]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[160]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[151]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[144]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[135]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[45]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[13]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[4]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[28]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[36]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[59]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[53]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[77]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[68]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[93]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[84]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[21]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[232]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[240]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[246]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[254]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[127]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[104]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[113]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[121]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[184]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[193]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[200]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[209]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[216]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[224]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[177]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[168]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[161]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[152]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[145]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[136]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[19]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[43]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[3]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[11]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[27]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[34]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[60]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[51]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[76]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[67]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[92]}]
set_property MARK_DEBUG true [get_nets {app_rd_data[83]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[62]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[5]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[59]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[94]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[85]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[70]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[55]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[46]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[39]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[30]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[23]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[14]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[228]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[236]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[244]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[252]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[120]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[108]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[101]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[116]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[132]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[141]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[145]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[171]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[180]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[188]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[196]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[204]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[212]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[220]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[156]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[148]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[54]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[29]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[6]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[45]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[61]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[69]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[78]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[86]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[92]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[38]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[22]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[13]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[227]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[234]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[243]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[250]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[124]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[103]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[99]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[115]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[131]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[140]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[147]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[155]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[164]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[172]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[178]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[186]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[195]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[202]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[211]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[218]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[43]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[11]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[4]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[27]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[93]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[84]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[76]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[67]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[53]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[37]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[21]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[213]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[229]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[237]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[253]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[127]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[109]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[102]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[117]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[137]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[151]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[157]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[163]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[181]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[197]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[223]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[207]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[189]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[174]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[166]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[135]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[52]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[3]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[60]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[68]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[74]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[82]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[91]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[44]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[36]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[28]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[20]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[12]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[230]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[238]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[246]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[254]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[125]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[110]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[100]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[118]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[133]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[142]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[149]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[158]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[165]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[173]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[182]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[190]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[198]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[205]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[214]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[222]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[75]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[50]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[1]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[18]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[89]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[98]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[83]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[66]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[58]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[42]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[34]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[26]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[10]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[232]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[241]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[245]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[248]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[128]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[105]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[113]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[121]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[184]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[193]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[200]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[209]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[216]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[225]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[175]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[169]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[161]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[152]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[144]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[136]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[64]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[2]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[16]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[57]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[73]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[81]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[90]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[97]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[48]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[41]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[32]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[25]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[7]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[231]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[240]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[247]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[255]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[126]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[104]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[111]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[119]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[192]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[199]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[208]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[215]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[224]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[183]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[176]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[167]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[159]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[150]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[143]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[134]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[49]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[8]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[0]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[17]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[88]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[77]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[80]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[71]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[65]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[51]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[35]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[33]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[19]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[235]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[242]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[251]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[112]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[107]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[114]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[123]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[129]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[170]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[187]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[194]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[203]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[206]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[219]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[221]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[179]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[162]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[153]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[139]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[56]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[15]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[63]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[72]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[79]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[87]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[96]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[47]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[40]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[31]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[24]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[9]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[233]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[239]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[249]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[130]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[95]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[106]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[122]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[191]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[201]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[210]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[217]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[226]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[185]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[177]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[168]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[160]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[154]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[146]}]
set_property MARK_DEBUG true [get_nets {app_wdf_data[138]}]
set_property MARK_DEBUG true [get_nets {state[0]}]
set_property MARK_DEBUG true [get_nets {state[1]}]
set_property MARK_DEBUG true [get_nets {state[2]}]
set_property MARK_DEBUG true [get_nets app_en]
set_property MARK_DEBUG true [get_nets app_rdy]
set_property MARK_DEBUG true [get_nets app_wdf_rdy]
set_property MARK_DEBUG true [get_nets app_wdf_wren]
set_property MARK_DEBUG true [get_nets calib_done]
set_property MARK_DEBUG true [get_nets ui_clk]
set_property MARK_DEBUG true [get_nets clk_200m]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_clk/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 256 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {app_rd_data[0]} {app_rd_data[1]} {app_rd_data[2]} {app_rd_data[3]} {app_rd_data[4]} {app_rd_data[5]} {app_rd_data[6]} {app_rd_data[7]} {app_rd_data[8]} {app_rd_data[9]} {app_rd_data[10]} {app_rd_data[11]} {app_rd_data[12]} {app_rd_data[13]} {app_rd_data[14]} {app_rd_data[15]} {app_rd_data[16]} {app_rd_data[17]} {app_rd_data[18]} {app_rd_data[19]} {app_rd_data[20]} {app_rd_data[21]} {app_rd_data[22]} {app_rd_data[23]} {app_rd_data[24]} {app_rd_data[25]} {app_rd_data[26]} {app_rd_data[27]} {app_rd_data[28]} {app_rd_data[29]} {app_rd_data[30]} {app_rd_data[31]} {app_rd_data[32]} {app_rd_data[33]} {app_rd_data[34]} {app_rd_data[35]} {app_rd_data[36]} {app_rd_data[37]} {app_rd_data[38]} {app_rd_data[39]} {app_rd_data[40]} {app_rd_data[41]} {app_rd_data[42]} {app_rd_data[43]} {app_rd_data[44]} {app_rd_data[45]} {app_rd_data[46]} {app_rd_data[47]} {app_rd_data[48]} {app_rd_data[49]} {app_rd_data[50]} {app_rd_data[51]} {app_rd_data[52]} {app_rd_data[53]} {app_rd_data[54]} {app_rd_data[55]} {app_rd_data[56]} {app_rd_data[57]} {app_rd_data[58]} {app_rd_data[59]} {app_rd_data[60]} {app_rd_data[61]} {app_rd_data[62]} {app_rd_data[63]} {app_rd_data[64]} {app_rd_data[65]} {app_rd_data[66]} {app_rd_data[67]} {app_rd_data[68]} {app_rd_data[69]} {app_rd_data[70]} {app_rd_data[71]} {app_rd_data[72]} {app_rd_data[73]} {app_rd_data[74]} {app_rd_data[75]} {app_rd_data[76]} {app_rd_data[77]} {app_rd_data[78]} {app_rd_data[79]} {app_rd_data[80]} {app_rd_data[81]} {app_rd_data[82]} {app_rd_data[83]} {app_rd_data[84]} {app_rd_data[85]} {app_rd_data[86]} {app_rd_data[87]} {app_rd_data[88]} {app_rd_data[89]} {app_rd_data[90]} {app_rd_data[91]} {app_rd_data[92]} {app_rd_data[93]} {app_rd_data[94]} {app_rd_data[95]} {app_rd_data[96]} {app_rd_data[97]} {app_rd_data[98]} {app_rd_data[99]} {app_rd_data[100]} {app_rd_data[101]} {app_rd_data[102]} {app_rd_data[103]} {app_rd_data[104]} {app_rd_data[105]} {app_rd_data[106]} {app_rd_data[107]} {app_rd_data[108]} {app_rd_data[109]} {app_rd_data[110]} {app_rd_data[111]} {app_rd_data[112]} {app_rd_data[113]} {app_rd_data[114]} {app_rd_data[115]} {app_rd_data[116]} {app_rd_data[117]} {app_rd_data[118]} {app_rd_data[119]} {app_rd_data[120]} {app_rd_data[121]} {app_rd_data[122]} {app_rd_data[123]} {app_rd_data[124]} {app_rd_data[125]} {app_rd_data[126]} {app_rd_data[127]} {app_rd_data[128]} {app_rd_data[129]} {app_rd_data[130]} {app_rd_data[131]} {app_rd_data[132]} {app_rd_data[133]} {app_rd_data[134]} {app_rd_data[135]} {app_rd_data[136]} {app_rd_data[137]} {app_rd_data[138]} {app_rd_data[139]} {app_rd_data[140]} {app_rd_data[141]} {app_rd_data[142]} {app_rd_data[143]} {app_rd_data[144]} {app_rd_data[145]} {app_rd_data[146]} {app_rd_data[147]} {app_rd_data[148]} {app_rd_data[149]} {app_rd_data[150]} {app_rd_data[151]} {app_rd_data[152]} {app_rd_data[153]} {app_rd_data[154]} {app_rd_data[155]} {app_rd_data[156]} {app_rd_data[157]} {app_rd_data[158]} {app_rd_data[159]} {app_rd_data[160]} {app_rd_data[161]} {app_rd_data[162]} {app_rd_data[163]} {app_rd_data[164]} {app_rd_data[165]} {app_rd_data[166]} {app_rd_data[167]} {app_rd_data[168]} {app_rd_data[169]} {app_rd_data[170]} {app_rd_data[171]} {app_rd_data[172]} {app_rd_data[173]} {app_rd_data[174]} {app_rd_data[175]} {app_rd_data[176]} {app_rd_data[177]} {app_rd_data[178]} {app_rd_data[179]} {app_rd_data[180]} {app_rd_data[181]} {app_rd_data[182]} {app_rd_data[183]} {app_rd_data[184]} {app_rd_data[185]} {app_rd_data[186]} {app_rd_data[187]} {app_rd_data[188]} {app_rd_data[189]} {app_rd_data[190]} {app_rd_data[191]} {app_rd_data[192]} {app_rd_data[193]} {app_rd_data[194]} {app_rd_data[195]} {app_rd_data[196]} {app_rd_data[197]} {app_rd_data[198]} {app_rd_data[199]} {app_rd_data[200]} {app_rd_data[201]} {app_rd_data[202]} {app_rd_data[203]} {app_rd_data[204]} {app_rd_data[205]} {app_rd_data[206]} {app_rd_data[207]} {app_rd_data[208]} {app_rd_data[209]} {app_rd_data[210]} {app_rd_data[211]} {app_rd_data[212]} {app_rd_data[213]} {app_rd_data[214]} {app_rd_data[215]} {app_rd_data[216]} {app_rd_data[217]} {app_rd_data[218]} {app_rd_data[219]} {app_rd_data[220]} {app_rd_data[221]} {app_rd_data[222]} {app_rd_data[223]} {app_rd_data[224]} {app_rd_data[225]} {app_rd_data[226]} {app_rd_data[227]} {app_rd_data[228]} {app_rd_data[229]} {app_rd_data[230]} {app_rd_data[231]} {app_rd_data[232]} {app_rd_data[233]} {app_rd_data[234]} {app_rd_data[235]} {app_rd_data[236]} {app_rd_data[237]} {app_rd_data[238]} {app_rd_data[239]} {app_rd_data[240]} {app_rd_data[241]} {app_rd_data[242]} {app_rd_data[243]} {app_rd_data[244]} {app_rd_data[245]} {app_rd_data[246]} {app_rd_data[247]} {app_rd_data[248]} {app_rd_data[249]} {app_rd_data[250]} {app_rd_data[251]} {app_rd_data[252]} {app_rd_data[253]} {app_rd_data[254]} {app_rd_data[255]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 256 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {app_wdf_data[0]} {app_wdf_data[1]} {app_wdf_data[2]} {app_wdf_data[3]} {app_wdf_data[4]} {app_wdf_data[5]} {app_wdf_data[6]} {app_wdf_data[7]} {app_wdf_data[8]} {app_wdf_data[9]} {app_wdf_data[10]} {app_wdf_data[11]} {app_wdf_data[12]} {app_wdf_data[13]} {app_wdf_data[14]} {app_wdf_data[15]} {app_wdf_data[16]} {app_wdf_data[17]} {app_wdf_data[18]} {app_wdf_data[19]} {app_wdf_data[20]} {app_wdf_data[21]} {app_wdf_data[22]} {app_wdf_data[23]} {app_wdf_data[24]} {app_wdf_data[25]} {app_wdf_data[26]} {app_wdf_data[27]} {app_wdf_data[28]} {app_wdf_data[29]} {app_wdf_data[30]} {app_wdf_data[31]} {app_wdf_data[32]} {app_wdf_data[33]} {app_wdf_data[34]} {app_wdf_data[35]} {app_wdf_data[36]} {app_wdf_data[37]} {app_wdf_data[38]} {app_wdf_data[39]} {app_wdf_data[40]} {app_wdf_data[41]} {app_wdf_data[42]} {app_wdf_data[43]} {app_wdf_data[44]} {app_wdf_data[45]} {app_wdf_data[46]} {app_wdf_data[47]} {app_wdf_data[48]} {app_wdf_data[49]} {app_wdf_data[50]} {app_wdf_data[51]} {app_wdf_data[52]} {app_wdf_data[53]} {app_wdf_data[54]} {app_wdf_data[55]} {app_wdf_data[56]} {app_wdf_data[57]} {app_wdf_data[58]} {app_wdf_data[59]} {app_wdf_data[60]} {app_wdf_data[61]} {app_wdf_data[62]} {app_wdf_data[63]} {app_wdf_data[64]} {app_wdf_data[65]} {app_wdf_data[66]} {app_wdf_data[67]} {app_wdf_data[68]} {app_wdf_data[69]} {app_wdf_data[70]} {app_wdf_data[71]} {app_wdf_data[72]} {app_wdf_data[73]} {app_wdf_data[74]} {app_wdf_data[75]} {app_wdf_data[76]} {app_wdf_data[77]} {app_wdf_data[78]} {app_wdf_data[79]} {app_wdf_data[80]} {app_wdf_data[81]} {app_wdf_data[82]} {app_wdf_data[83]} {app_wdf_data[84]} {app_wdf_data[85]} {app_wdf_data[86]} {app_wdf_data[87]} {app_wdf_data[88]} {app_wdf_data[89]} {app_wdf_data[90]} {app_wdf_data[91]} {app_wdf_data[92]} {app_wdf_data[93]} {app_wdf_data[94]} {app_wdf_data[95]} {app_wdf_data[96]} {app_wdf_data[97]} {app_wdf_data[98]} {app_wdf_data[99]} {app_wdf_data[100]} {app_wdf_data[101]} {app_wdf_data[102]} {app_wdf_data[103]} {app_wdf_data[104]} {app_wdf_data[105]} {app_wdf_data[106]} {app_wdf_data[107]} {app_wdf_data[108]} {app_wdf_data[109]} {app_wdf_data[110]} {app_wdf_data[111]} {app_wdf_data[112]} {app_wdf_data[113]} {app_wdf_data[114]} {app_wdf_data[115]} {app_wdf_data[116]} {app_wdf_data[117]} {app_wdf_data[118]} {app_wdf_data[119]} {app_wdf_data[120]} {app_wdf_data[121]} {app_wdf_data[122]} {app_wdf_data[123]} {app_wdf_data[124]} {app_wdf_data[125]} {app_wdf_data[126]} {app_wdf_data[127]} {app_wdf_data[128]} {app_wdf_data[129]} {app_wdf_data[130]} {app_wdf_data[131]} {app_wdf_data[132]} {app_wdf_data[133]} {app_wdf_data[134]} {app_wdf_data[135]} {app_wdf_data[136]} {app_wdf_data[137]} {app_wdf_data[138]} {app_wdf_data[139]} {app_wdf_data[140]} {app_wdf_data[141]} {app_wdf_data[142]} {app_wdf_data[143]} {app_wdf_data[144]} {app_wdf_data[145]} {app_wdf_data[146]} {app_wdf_data[147]} {app_wdf_data[148]} {app_wdf_data[149]} {app_wdf_data[150]} {app_wdf_data[151]} {app_wdf_data[152]} {app_wdf_data[153]} {app_wdf_data[154]} {app_wdf_data[155]} {app_wdf_data[156]} {app_wdf_data[157]} {app_wdf_data[158]} {app_wdf_data[159]} {app_wdf_data[160]} {app_wdf_data[161]} {app_wdf_data[162]} {app_wdf_data[163]} {app_wdf_data[164]} {app_wdf_data[165]} {app_wdf_data[166]} {app_wdf_data[167]} {app_wdf_data[168]} {app_wdf_data[169]} {app_wdf_data[170]} {app_wdf_data[171]} {app_wdf_data[172]} {app_wdf_data[173]} {app_wdf_data[174]} {app_wdf_data[175]} {app_wdf_data[176]} {app_wdf_data[177]} {app_wdf_data[178]} {app_wdf_data[179]} {app_wdf_data[180]} {app_wdf_data[181]} {app_wdf_data[182]} {app_wdf_data[183]} {app_wdf_data[184]} {app_wdf_data[185]} {app_wdf_data[186]} {app_wdf_data[187]} {app_wdf_data[188]} {app_wdf_data[189]} {app_wdf_data[190]} {app_wdf_data[191]} {app_wdf_data[192]} {app_wdf_data[193]} {app_wdf_data[194]} {app_wdf_data[195]} {app_wdf_data[196]} {app_wdf_data[197]} {app_wdf_data[198]} {app_wdf_data[199]} {app_wdf_data[200]} {app_wdf_data[201]} {app_wdf_data[202]} {app_wdf_data[203]} {app_wdf_data[204]} {app_wdf_data[205]} {app_wdf_data[206]} {app_wdf_data[207]} {app_wdf_data[208]} {app_wdf_data[209]} {app_wdf_data[210]} {app_wdf_data[211]} {app_wdf_data[212]} {app_wdf_data[213]} {app_wdf_data[214]} {app_wdf_data[215]} {app_wdf_data[216]} {app_wdf_data[217]} {app_wdf_data[218]} {app_wdf_data[219]} {app_wdf_data[220]} {app_wdf_data[221]} {app_wdf_data[222]} {app_wdf_data[223]} {app_wdf_data[224]} {app_wdf_data[225]} {app_wdf_data[226]} {app_wdf_data[227]} {app_wdf_data[228]} {app_wdf_data[229]} {app_wdf_data[230]} {app_wdf_data[231]} {app_wdf_data[232]} {app_wdf_data[233]} {app_wdf_data[234]} {app_wdf_data[235]} {app_wdf_data[236]} {app_wdf_data[237]} {app_wdf_data[238]} {app_wdf_data[239]} {app_wdf_data[240]} {app_wdf_data[241]} {app_wdf_data[242]} {app_wdf_data[243]} {app_wdf_data[244]} {app_wdf_data[245]} {app_wdf_data[246]} {app_wdf_data[247]} {app_wdf_data[248]} {app_wdf_data[249]} {app_wdf_data[250]} {app_wdf_data[251]} {app_wdf_data[252]} {app_wdf_data[253]} {app_wdf_data[254]} {app_wdf_data[255]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {state[0]} {state[1]} {state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list app_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list app_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list app_wdf_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list app_wdf_wren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list calib_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list ui_clk]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list clk_50m]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200m]
